apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-nginx-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - host: assignment.jay.cloud-ip.cc
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fast-api-frontend-svc
                port:
                  number: 80
    - host: assignment-api.jay.cloud-ip.cc
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fast-api-backend-svc
                port:
                  number: 8000