apiVersion: apps/v1
kind: Deployment
metadata:
  name: fast-api-frontend
spec:
  selector:
    matchLabels:
      app: fast-api-frontend
  template:
    metadata:
      labels:
        app: fast-api-frontend
    spec:
      containers:
      - name: fast-api-frontend
        image: 935456168005.dkr.ecr.ap-south-1.amazonaws.com/assignment-frontend:latest
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

--- 

apiVersion: v1
kind: Service
metadata:
  name: fast-api-frontend-svc
spec:
  type: ClusterIP
  selector:
    app: fast-api-frontend
  ports:
  - port: 80
    targetPort: 80
