apiVersion: v1
data:
  BACKEND_CORS_ORIGINS: aHR0cDovL2xvY2FsaG9zdCxodHRwOi8vbG9jYWxob3N0OjUxNzMsaHR0cDovL2Fzc2lnbm1lbnQuamF5LmNsb3VkLWlwLmNj
  DOMAIN: bG9jYWxob3N0
  EMAILS_FROM_EMAIL: aW5mb0BleGFtcGxlLmNvbQ==
  ENVIRONMENT: bG9jYWw=
  FIRST_SUPERUSER: aGFybmVzaGEyMkBnbWFpbC5jb20=
  FIRST_SUPERUSER_PASSWORD: aGFybmVzaGEyMg==
  POSTGRES_DB: YXNzaWdubWVudGRldmRi
  POSTGRES_PASSWORD: UHBRRjBlZ0lXX3ZLNCFSMjJVaFhTKFh5RnRdRg==
  POSTGRES_PORT: NTQzMg==
  POSTGRES_SERVER: Z2Fzc2lnbm1lbnQtZGV2LWRiLmMxMGswazg2dTc5cy5hcC1zb3V0aC0xLnJkcy5hbWF6b25hd3MuY29t
  POSTGRES_USER: YXNzaWdubWVudF9kZXZfZGI=
  PROJECT_NAME: RnVsbCBTdGFjayBGYXN0QVBJIFByb2plY3Q=
  SECRET_KEY: aGFybmVzaGEyMjQ0
  SMTP_HOST: ""
  SMTP_PASSWORD: ""
  SMTP_PORT: NTg3
  SMTP_SSL: RmFsc2U=
  SMTP_TLS: VHJ1ZQ==
  SMTP_USER: ""
  STACK_NAME: ZnVsbC1zdGFjay1mYXN0YXBpLXByb2plY3Q=
  USERS_OPEN_REGISTRATION: VHJ1ZQ==
kind: Secret
metadata:
  name: backend-secret
