name: CI-CD Pipeline

on:
  workflow_dispatch:
  push:
    branches: [ "dev" ]


env:
  AWS_REGION: ap-south-1
  ECR_BACKEND_REPO: genea-assignment-backend
  ECR_FRONTEND_REPO: genea-assignment-frontend
  EKS_CLUSTER_NAME: genea-assignment-cluster
  IMAGE_TAG: ${{ github.sha }}

jobs:
  pre-build:
    name: pre-build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: pip install poetry

      - name: Install backend dependencies
        working-directory: application/backend
        run: poetry install

      # - name: Run backend tests
      #   working-directory: application/backend
      #   run: poetry run pytest

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install frontend dependencies
        working-directory: application/frontend
        run: npm ci

      - name: Build frontend
        working-directory: application/frontend
        run: npm run build

  build:
    name: build
    runs-on: ubuntu-latest
    needs: pre-build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::935456168005:role/GitHubAction-AssumeRoleWithAction
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & push backend image
        working-directory: application/backend
        run: |
          docker build -t $ECR_BACKEND_REPO:${IMAGE_TAG} application/backend
          docker tag $ECR_BACKEND_REPO:${IMAGE_TAG} \
            ${{ steps.ecr.outputs.registry }}/$ECR_BACKEND_REPO:${IMAGE_TAG}
          docker push ${{ steps.ecr.outputs.registry }}/$ECR_BACKEND_REPO:${IMAGE_TAG}

      - name: Build & push frontend image
        working-directory: application/frontend
        run: |
          docker build -t $ECR_FRONTEND_REPO:${IMAGE_TAG} application/frontend
          docker tag $ECR_FRONTEND_REPO:${IMAGE_TAG} \
            ${{ steps.ecr.outputs.registry }}/$ECR_FRONTEND_REPO:${IMAGE_TAG}
          docker push ${{ steps.ecr.outputs.registry }}/$ECR_FRONTEND_REPO:${IMAGE_TAG}

      # ########################
      # # Deploy to EKS
      # ########################
      # - name: Update kubeconfig
      #   run: |
      #     aws eks update-kubeconfig \
      #       --name $EKS_CLUSTER_NAME \
      #       --region $AWS_REGION

      # - name: Deploy to EKS
      #   run: |
      #     kubectl rollout restart deployment backend
      #     kubectl rollout restart deployment frontend
