name: CI-CD Pipeline

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - closed
      - synchronize
  push:
    branches: [ "dev" ]


env:
  AWS_REGION: ap-south-1
  ECR_BACKEND_REPO: assignment-backend
  ECR_FRONTEND_REPO: assignment-frontend
  EKS_CLUSTER_NAME: assignment-cluster
  VITE_API_URL: http://assignment-api.jay.cloud-ip.cc
  IMAGE_TAG: ${{ github.sha }}

jobs:

  ci:
    name: ci-jobs
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::935456168005:role/GitHubAction-AssumeRoleWithAction
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & push backend image
        working-directory: application/backend
        run: |
          docker build -t $ECR_BACKEND_REPO:${IMAGE_TAG} .
          docker tag $ECR_BACKEND_REPO:${IMAGE_TAG} \
            ${{ steps.ecr.outputs.registry }}/$ECR_BACKEND_REPO:latest
          docker tag $ECR_BACKEND_REPO:${IMAGE_TAG} \
            ${{ steps.ecr.outputs.registry }}/$ECR_BACKEND_REPO:${IMAGE_TAG}
          docker push ${{ steps.ecr.outputs.registry }}/$ECR_BACKEND_REPO:${IMAGE_TAG}
          docker push ${{ steps.ecr.outputs.registry }}/$ECR_BACKEND_REPO:latest 

      - name: Build & push frontend image
        working-directory: application/frontend
        run: |
          docker build \
            --build-arg VITE_API_URL=${VITE_API_URL} \
            -t $ECR_FRONTEND_REPO:${IMAGE_TAG} .
          docker tag $ECR_FRONTEND_REPO:${IMAGE_TAG} \
            ${{ steps.ecr.outputs.registry }}/$ECR_FRONTEND_REPO:${IMAGE_TAG}
          docker tag $ECR_FRONTEND_REPO:${IMAGE_TAG} \
            ${{ steps.ecr.outputs.registry }}/$ECR_FRONTEND_REPO:latest
          docker push ${{ steps.ecr.outputs.registry }}/$ECR_FRONTEND_REPO:${IMAGE_TAG}
          docker push ${{ steps.ecr.outputs.registry }}/$ECR_FRONTEND_REPO:latest
  cd:
    name: cd-jobs
    needs: ci
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::935456168005:role/GitHubAction-AssumeRoleWithAction
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup EKS Kubeconfig
        run: |
          aws eks update-kubeconfig \
            --name $EKS_CLUSTER_NAME \
            --region $AWS_REGION
          kubectl cluster-info

      - name: Deploy Backend
        run: |
          kubectl set image deployment/fast-api-backend \
            fast-api-backend=${{ env.ECR_BACKEND_REPO }}:${{ env.IMAGE_TAG }} \
            --record
          kubectl rollout status deployment/fast-api-backend --timeout=30s

      - name: Deploy Frontend
        run: |
          kubectl set image deployment/fast-api-frontend \
            fast-api-frontend=${{ env.ECR_FRONTEND_REPO }}:${{ env.IMAGE_TAG }} \
            --record
          kubectl rollout status deployment/fast-api-frontend --timeout=30s

      - name: Verify Deployment
        run: | 
          kubectl rollout history deployment/fast-api-backend
          kubectl rollout history deployment/fast-api-frontend
